### ISSUE TITLE
Paper Up For Grab: The lottery ticket hypothesis

### ISSUE THREAD

**Issue by yongzx** [nplan-io/ml_paper_club#2]
@caledezma  @gante  @Mchristos  I would love to present the paper Frankle, J., & Carbin, M. (2018). The lottery ticket hypothesis: Finding sparse, trainable neural networks. arXiv preprint arXiv:1803.03635. How would it work if I would love to be a presenter?

**Comment by caledezma** [comment]
Hello, please send us an email (carlos@nplan.io/joao@nplan.io) saying when you would like to present and we will schedule it with you.
